In [52]:
import numpy as np
import numpy
import pandas as pd
from pandas import read_csv
import warnings
warnings.filterwarnings('ignore')

In [53]:
# load data
SP20 = read_csv('SP20.csv', delimiter=",", low_memory=False, keep_default_na=False)

In [54]:
SP21 = read_csv('SP21.csv', delimiter=",", low_memory=False, keep_default_na=False)

In [55]:
SP20 = SP20[ ['month', 'year','FEBRE','TOSSE','GARGANTA','DISPNEIA','DESC_RESP','SATURACAO','DIARREIA','VOMITO',
                  'DOR_ABD','FADIGA','PERD_OLFT','PERD_PALA'] ]

In [56]:
SP20

,month,year,FEBRE,TOSSE,GARGANTA,DISPNEIA,DESC_RESP,SATURACAO,DIARREIA,VOMITO,DOR_ABD,FADIGA,PERD_OLFT,PERD_PALA
0,1,2020,1,1,0,0,0,0,1,0,0,0,0,0
1,1,2020,1,1,1,1,1,1,0,0,0,0,0,0
2,1,2020,1,1,0,1,1,1,0,0,0,0,0,0
3,1,2020,1,1,0,0,1,0,0,0,0,0,0,0
4,1,2020,1,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170483,12,2020,0,0,0,0,0,0,0,0,0,0,0,0
170484,12,2020,1,1,1,0,0,0,0,0,0,0,0,0
170485,12,2020,0,0,0,0,0,1,0,0,0,1,0,0
170486,12,2020,1,1,0,1,0,1,0,0,0,1,1,1
170487,12,2020,0,1,0,1,1,1,0,0,0,0,0,0

In [57]:
SP21 = SP21[ ['month', 'year','FEBRE','TOSSE','GARGANTA','DISPNEIA','DESC_RESP','SATURACAO','DIARREIA','VOMITO',
                  'DOR_ABD','FADIGA','PERD_OLFT','PERD_PALA'] ]

In [58]:
SP20 = SP20.rename(columns={"FEBRE":"fever", "TOSSE":"cough", "GARGANTA":"throat", 'DISPNEIA':'dyspnoea', 'DESC_RESP': 'respdesc', 'SATURACAO':'saturation', 'DIARREIA':'diarrhoea', 'VOMITO':'vomit', 'DOR_ABD':'abdpain', "FADIGA":"fatigue", 'PERD_OLFT':'lossm', 'PERD_PALA':'losst'})

In [59]:
SP21 = SP21.rename(columns={"FEBRE":"fever", "TOSSE":"cough", "GARGANTA":"throat", 'DISPNEIA':'dyspnoea', 'DESC_RESP': 'respdesc', 'SATURACAO':'saturation', 'DIARREIA':'diarrhoea', 'VOMITO':'vomit', 'DOR_ABD':'abdpain', "FADIGA":"fatigue", 'PERD_OLFT':'lossm', 'PERD_PALA':'losst'})

In [60]:
SP20

,month,year,fever,cough,throat,dyspnoea,respdesc,saturation,diarrhoea,vomit,abdpain,fatigue,lossm,losst
0,1,2020,1,1,0,0,0,0,1,0,0,0,0,0
1,1,2020,1,1,1,1,1,1,0,0,0,0,0,0
2,1,2020,1,1,0,1,1,1,0,0,0,0,0,0
3,1,2020,1,1,0,0,1,0,0,0,0,0,0,0
4,1,2020,1,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170483,12,2020,0,0,0,0,0,0,0,0,0,0,0,0
170484,12,2020,1,1,1,0,0,0,0,0,0,0,0,0
170485,12,2020,0,0,0,0,0,1,0,0,0,1,0,0
170486,12,2020,1,1,0,1,0,1,0,0,0,1,1,1
170487,12,2020,0,1,0,1,1,1,0,0,0,0,0,0

In [61]:
SP21

,month,year,fever,cough,throat,dyspnoea,respdesc,saturation,diarrhoea,vomit,abdpain,fatigue,lossm,losst
0,1,2021,0,1,0,1,1,0,0,0,0,1,0,0
1,1,2021,1,1,1,1,1,1,0,0,0,0,0,0
2,1,2021,1,1,0,1,1,1,0,0,0,1,0,0
3,1,2021,1,1,1,0,0,1,0,0,0,0,0,0
4,1,2021,1,1,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213440,7,2023,1,1,0,1,1,1,0,0,0,1,0,0
213441,7,2023,1,1,0,1,1,1,0,0,0,0,0,0
213442,8,2023,0,1,0,1,1,1,0,0,0,1,0,0
213443,8,2023,0,0,0,1,1,1,0,0,0,0,0,0
213444,8,2023,1,0,0,1,1,1,0,0,0,0,0,0

In [62]:
SP20 = SP20[ ['month', 'year','fever','cough','throat','dyspnoea','respdesc','saturation','diarrhoea','vomit', 'abdpain',
                  'fatigue','lossm','losst'] ]

In [63]:
SP21 = SP21[ ['month', 'year', 'fever','cough','throat','dyspnoea','respdesc','saturation','diarrhoea','vomit', 'abdpain',
                  'fatigue','lossm','losst'] ]

In [41]:
SP20.to_csv("SP20_final.csv", index=False)

In [42]:
SP21.to_csv("SP21_final.csv", index=False)